### ISSUE TITLE
FileNotFoundError: [WinError 2] System can't find specified file

### ISSUE THREAD

**Issue by kaufmann-dev** [HelpSeeker/Restricted-WebM#2]
Script can't find some file, I have FFMpeg, FFProbe, restrict.py and input.webm on desktop. Idk if I'm doing something wrong or there's an error with your script or my computer.
![1](https://user-images.githubusercontent.com/47983391/96188378-ea67eb00-0f3e-11eb-8961-fb7dd50ca474.PNG)

**Comment by HelpSeeker** [comment]
FFmpeg and FFprobe need to be part of your PATH for this script to work. The problem is that it changes into the output folder (in your case Desktop\webm_done) for the conversion, so it doesn't have access to the local executables anymore.

For now add those two executables to your PATH and it should work. Putting FFmpeg/FFprobe next to the script should be a viable option though, so I'll soon update the script to work with absolute output paths instead of changing directories.

**Comment by kaufmann-dev** [comment]
Thank you, this solved my problem.

**Comment by HelpSeeker** [comment]
Now local excecutables can be used without adding them to your PATH, IF you use CMD to run the script. Unfortunately (at least for this script) Un*x shells and Powershell are not as lax when it comes to calling local executables by name, so for now they still require FFmpeg/ffprobe in the PATH.
